// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_IVoa7IV0xeSZqddVJcS3Ogb0K0qKyL0',
    appId: '1:266686473772:web:016edb075255dd36ab9389',
    messagingSenderId: '266686473772',
    projectId: 'hackoverflow-2725e',
    authDomain: 'hackoverflow-2725e.firebaseapp.com',
    databaseURL: 'https://hackoverflow-2725e-default-rtdb.firebaseio.com',
    storageBucket: 'hackoverflow-2725e.appspot.com',
    measurementId: 'G-YZ23K2BBG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCywtRm-uGxs4N87yHpjje8cQE7P9s7IKE',
    appId: '1:266686473772:android:7be166a55c1399a9ab9389',
    messagingSenderId: '266686473772',
    projectId: 'hackoverflow-2725e',
    databaseURL: 'https://hackoverflow-2725e-default-rtdb.firebaseio.com',
    storageBucket: 'hackoverflow-2725e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7_khvsZQDQ_m1eV55_Jme_jsYBkDlxdw',
    appId: '1:266686473772:ios:ba879b772317f353ab9389',
    messagingSenderId: '266686473772',
    projectId: 'hackoverflow-2725e',
    databaseURL: 'https://hackoverflow-2725e-default-rtdb.firebaseio.com',
    storageBucket: 'hackoverflow-2725e.appspot.com',
    iosBundleId: 'com.citizenProblems.abondonVehicle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7_khvsZQDQ_m1eV55_Jme_jsYBkDlxdw',
    appId: '1:266686473772:ios:ba879b772317f353ab9389',
    messagingSenderId: '266686473772',
    projectId: 'hackoverflow-2725e',
    databaseURL: 'https://hackoverflow-2725e-default-rtdb.firebaseio.com',
    storageBucket: 'hackoverflow-2725e.appspot.com',
    iosBundleId: 'com.citizenProblems.abondonVehicle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhG5Uy0Jtx0KOA1gRZ3GEdEXTt3o29YNY',
    appId: '1:266686473772:web:832b21fbf28da06aab9389',
    messagingSenderId: '266686473772',
    projectId: 'hackoverflow-2725e',
    authDomain: 'hackoverflow-2725e.firebaseapp.com',
    databaseURL: 'https://hackoverflow-2725e-default-rtdb.firebaseio.com',
    storageBucket: 'hackoverflow-2725e.appspot.com',
    measurementId: 'G-8XKR40GEYE',
  );

}